from typing import Optional
from sqlalchemy import String, Integer, BigInteger, Text, LargeBinary, CHAR, VARCHAR
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass

class Vs(Base):
    __tablename__ = "vs"

    auto: Mapped[int] = mapped_column("vs_auto", BigInteger, primary_key=True, autoincrement=True)
    saup: Mapped[str] = mapped_column("vs_saup", VARCHAR(2), nullable=False)
    chart: Mapped[str] = mapped_column("vs_chart", VARCHAR(8), nullable=False)
    ibymd: Mapped[str] = mapped_column("vs_ibymd", VARCHAR(8), nullable=False)
    ymd: Mapped[str] = mapped_column("vs_ymd", VARCHAR(8), nullable=False)
    time: Mapped[str] = mapped_column("vs_time", VARCHAR(6), nullable=False)
    teymd: Mapped[Optional[str]] = mapped_column("vs_teymd", VARCHAR(8), default="")
    yuhyung: Mapped[Optional[str]] = mapped_column("vs_yuhyung", VARCHAR(2), default="")
    bscode: Mapped[Optional[str]] = mapped_column("vs_bscode", VARCHAR(9), default="")
    jinchal: Mapped[Optional[str]] = mapped_column("vs_jinchal", VARCHAR(2), default="")
    suname: Mapped[Optional[str]] = mapped_column("vs_suname", VARCHAR(50), default="")
    jumin: Mapped[Optional[str]] = mapped_column("vs_jumin", VARCHAR(48), default="")
    nurse: Mapped[Optional[str]] = mapped_column("vs_nurse", VARCHAR(10), default="")
    weymd: Mapped[Optional[str]] = mapped_column("vs_weymd", VARCHAR(8), default="")
    hulap1: Mapped[Optional[str]] = mapped_column("vs_hulap1", VARCHAR(10), default="")
    hulap2: Mapped[Optional[str]] = mapped_column("vs_hulap2", VARCHAR(10), default="")
    maekbak: Mapped[Optional[str]] = mapped_column("vs_maekbak", VARCHAR(10), default="")
    cheon: Mapped[Optional[str]] = mapped_column("vs_cheon", VARCHAR(10), default="")
    hohup: Mapped[Optional[str]] = mapped_column("vs_hohup", VARCHAR(10), default="")
    weight: Mapped[Optional[str]] = mapped_column("vs_weight", VARCHAR(10), default="")
    height: Mapped[Optional[str]] = mapped_column("vs_height", VARCHAR(10), default="")
    bmi: Mapped[Optional[str]] = mapped_column("vs_bmi", VARCHAR(10), default="")
    intake: Mapped[Optional[str]] = mapped_column("vs_intake", VARCHAR(10), default="")
    urine: Mapped[Optional[str]] = mapped_column("vs_urine", VARCHAR(16), default="")
    stools: Mapped[Optional[str]] = mapped_column("vs_stools", VARCHAR(16), default="")
    fluids: Mapped[Optional[str]] = mapped_column("vs_fluids", VARCHAR(16), default="")
    blood: Mapped[Optional[str]] = mapped_column("vs_blood", VARCHAR(16), default="")
    aspiration: Mapped[Optional[str]] = mapped_column("vs_aspiration", VARCHAR(16), default="")
    drainage: Mapped[Optional[str]] = mapped_column("vs_drainage", VARCHAR(16), default="")
    vomitus: Mapped[Optional[str]] = mapped_column("vs_vomitus", VARCHAR(16), default="")
    username: Mapped[Optional[str]] = mapped_column("vs_username", VARCHAR(20), default="")
    glucose: Mapped[Optional[str]] = mapped_column("vs_glucose", VARCHAR(20), default="")
    spo2: Mapped[Optional[str]] = mapped_column("vs_spo2", VARCHAR(20), default="")
    etc1: Mapped[Optional[str]] = mapped_column("vs_etc1", VARCHAR(255), default="")
    etc2: Mapped[Optional[str]] = mapped_column("vs_etc2", VARCHAR(255), default="")
    etc3: Mapped[Optional[str]] = mapped_column("vs_etc3", VARCHAR(255), default="")
    etc4: Mapped[Optional[str]] = mapped_column("vs_etc4", VARCHAR(255), default="")
    etc5: Mapped[Optional[str]] = mapped_column("vs_etc5", VARCHAR(255), default="")
    dc: Mapped[str] = mapped_column("vs_dc", CHAR(1), nullable=False, default="0")
    indate: Mapped[Optional[str]] = mapped_column("vs_indate", VARCHAR(20), default="")
    update: Mapped[Optional[str]] = mapped_column("vs_update", VARCHAR(20), default="")
    dcdate: Mapped[Optional[str]] = mapped_column("vs_dcdate", VARCHAR(20), default="")
    upuser: Mapped[Optional[str]] = mapped_column("vs_upuser", VARCHAR(20), default="")
    dcuser: Mapped[Optional[str]] = mapped_column("vs_dcuser", VARCHAR(20), default="")
    insign: Mapped[Optional[bytes]] = mapped_column("vs_insign", LargeBinary)
    upsign: Mapped[Optional[bytes]] = mapped_column("vs_upsign", LargeBinary)
    dcsign: Mapped[Optional[bytes]] = mapped_column("vs_dcsign", LargeBinary)
    incert: Mapped[Optional[str]] = mapped_column("vs_incert", Text)
    upcert: Mapped[Optional[str]] = mapped_column("vs_upcert", Text)
    dccert: Mapped[Optional[str]] = mapped_column("vs_dccert", Text)
    etc6: Mapped[Optional[str]] = mapped_column("vs_etc6", VARCHAR(255), default="")
    etc7: Mapped[Optional[str]] = mapped_column("vs_etc7", VARCHAR(255), default="")
    etc8: Mapped[Optional[str]] = mapped_column("vs_etc8", VARCHAR(255), default="")
    etc9: Mapped[Optional[str]] = mapped_column("vs_etc9", VARCHAR(255), default="")
    etc10: Mapped[Optional[str]] = mapped_column("vs_etc10", VARCHAR(255), default="")
    shift: Mapped[Optional[str]] = mapped_column("vs_shift", VARCHAR(1), default="D")
